server:
  - name: Server Name
    key: ServerDescription_Persistent/ServerName
    type: str
    group: Basic
    help: "Name of your server. Useful for distinguishing servers with similar invite codes."
  - name: Invite Code
    key: ServerDescription_Persistent/InviteCode
    type: str
    group: Basic
    help: "Invite code used to find your server. Allowed characters: 0–9, a–z, A–Z. Must contain at least 6 characters. Case-sensitive."
  - name: Password Protected
    key: ServerDescription_Persistent/IsPasswordProtected
    type: bool
    default: false
    group: Basic
    help: "Specifies whether a password is required."
  - name: Password
    key: ServerDescription_Persistent/Password
    type: str
    group: Basic
    help: "The password required to join the server."
  - name: World Island ID
    key: ServerDescription_Persistent/WorldIslandID
    type: str
    help: "ID of the selected world. Must match the corresponding value in one of the server's WorldDescription.json files."
  - name: Max Player Count
    key: ServerDescription_Persistent/MaxPlayerCount
    type: int
    default: 8
    help: "Maximum number of players allowed on the server."
  - name: Use Direct Connection
    key: ServerDescription_Persistent/UseDirectConnection
    type: bool
    default: false
    help: "Specifies whether to use direct connection for the server."
  - name: Direct Connection Server Port
    key: ServerDescription_Persistent/DirectConnectionServerPort
    type: int
    default: 7777
    help: "Port number for direct connection server."
manager:
  - name: Steam Branch
    section: Steam
    key: steam_branch
    type: str
    default: public
    help: "The Steam branch to install the server from (e.g., stable, experimental)."
    group: Settings
  - name: Steam Branch Password
    section: Steam
    key: steam_branch_password
    type: str
    default: ""
    help: "The password for accessing a private Steam branch, if applicable."
    group: Settings
  - name: Default Proton Path
    key: defaultprotonpath
    section: Environment
    type: str
    help: "The default Proton path to use for new servers."
  - name: Delayed Shutdown Warning
    section: Messages
    key: shutdown_delayed
    type: str
    default: Server is shutting down in {time} minutes
    help: "Custom message broadcasted to players every 5 minutes before a delayed server shutdown.  Use '{time}' to replace with number of minutes remaining"
  - name: Delayed Restart Warning
    section: Messages
    key: restart_delayed
    type: str
    default: Server is restarting in {time} minutes
    help: "Custom message broadcasted to players every 5 minutes before a delayed server restart.  Use '{time}' to replace with number of minutes remaining"
  - name: Delayed Update Warning
    section: Messages
    key: update_delayed
    type: str
    default: Server is updating in {time} minutes
    help: "Custom message broadcasted to players every 5 minutes before a delayed server update.  Use '{time}' to replace with number of minutes remaining"
  - name: Shutdown Warning 5 Minutes
    section: Messages
    key: shutdown_5min
    type: str
    default: Server is shutting down in 5 minutes
    help: "Custom message broadcasted to players 5 minutes before server shutdown."
  - name: Shutdown Warning 4 Minutes
    section: Messages
    key: shutdown_4min
    type: str
    default: Server is shutting down in 4 minutes
    help: "Custom message broadcasted to players 4 minutes before server shutdown."
  - name: Shutdown Warning 3 Minutes
    section: Messages
    key: shutdown_3min
    type: str
    default: Server is shutting down in 3 minutes
    help: "Custom message broadcasted to players 3 minutes before server shutdown."
  - name: Shutdown Warning 2 Minutes
    section: Messages
    key: shutdown_2min
    type: str
    default: Server is shutting down in 2 minutes
    help: "Custom message broadcasted to players 2 minutes before server shutdown."
  - name: Shutdown Warning 1 Minute
    section: Messages
    key: shutdown_1min
    type: str
    default: Server is shutting down in 1 minute
    help: "Custom message broadcasted to players 1 minute before server shutdown."
  - name: Shutdown Warning 30 Seconds
    section: Messages
    key: shutdown_30sec
    type: str
    default: Server is shutting down in 30 seconds!
    help: "Custom message broadcasted to players 30 seconds before server shutdown."
  - name: Shutdown Warning NOW
    section: Messages
    key: shutdown_now
    type: str
    default: Server is shutting down NOW!
    help: "Custom message broadcasted to players immediately before server shutdown."
  - name: Instance Started (Discord)
    section: Discord
    key: instance_started
    type: str
    default: "{instance} has started! :rocket:"
    help: "Custom message sent to Discord when the server starts, use '{instance}' to insert the map name"
  - name: Instance Stopping (Discord)
    section: Discord
    key: instance_stopping
    type: str
    default: ":small_red_triangle_down: {instance} is shutting down"
    help: "Custom message sent to Discord when the server stops, use '{instance}' to insert the map name"
  - name: Discord Enabled
    section: Discord
    key: enabled
    type: bool
    default: false
    help: "Enables or disables Discord integration for server status updates."
  - name: Discord Webhook URL
    section: Discord
    key: webhook
    type: str
    help: "The webhook URL for sending server status updates to a Discord channel."
service:
  - name: Proton Path
    key: protonpath
    section: system
    group: Settings
    type: str
    help: "The Proton path to use for this instance."
